# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDePreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tomada', models.CharField(default='', help_text='Número da Consulta de Preço', max_length=100, unique=True, verbose_name='Número da Consulta')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credor.CredorFornecedor', verbose_name='Credor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDeDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterialDeConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_unitario', models.CharField(max_length=100, verbose_name='Valor Unitário')),
                ('tipo_de_medida', models.CharField(max_length=100, verbose_name='Tipo de Unidade de Medida')),
            ],
        ),
        migrations.CreateModel(
            name='MapaComparativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menor_preco', models.CharField(blank=True, default='', max_length=100, verbose_name='Menor Preço: ')),
                ('preco_medio', models.CharField(blank=True, default='', max_length=100, verbose_name='Preço Médio:')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credor.CredorFornecedor', verbose_name='Credor')),
                ('tomada1', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tomada_de_preco1', to='processo_pagamento.ConsultaDePreco', verbose_name='Tomada 1')),
                ('tomada2', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tomada_de_preco2', to='processo_pagamento.ConsultaDePreco', verbose_name='Tomada 2')),
                ('tomada3', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tomada_de_preco3', to='processo_pagamento.ConsultaDePreco', verbose_name='Tomada 3')),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaDaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código Natureza da Despesa')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.CharField(default='', help_text='Número da Ordem de Preço', max_length=100, unique=True, verbose_name='Número da Ordem')),
                ('consulta_vencedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_pagamento.MapaComparativo')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(default='', help_text='Número do Processo', max_length=100, unique=True, verbose_name='Número do Processo')),
                ('numero_memorando', models.CharField(default='', help_text='Número do Memorando', max_length=100, unique=True, verbose_name='Número do Memorando')),
                ('natureza_despesa', models.CharField(choices=[('Diárias [33.90.14.00', 'Diárias [33.90.14.00'), ('Materia de Consumo [33.90.30.00]', 'Materia de Consumo [33.90.30.00]'), ('Serviços de Pessoa Física [33.90.36.00]', 'Serviços de Pessoa Física [33.90.36.00]'), ('Serviços de Pessoa Jurídica [33.90.39.00]', 'Serviços de Pessoa Jurídica [33.90.39.00]')], max_length=100, verbose_name='Natureza da Despesa')),
                ('valor_bruto', models.CharField(blank=True, default='', help_text='Valor Bruto', max_length=100, verbose_name='Valor')),
                ('data_cricacao', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('numero_empenho', models.CharField(blank=True, default='', help_text='Número da Nota de Empenho', max_length=100, verbose_name='NE')),
                ('nota_empenho', models.FileField(blank=True, help_text='Nota de Empenho em Formato PDF', upload_to='empenhoProcesso/%d/%m/%Y/')),
                ('numero_liquidacao', models.CharField(blank=True, default='', max_length=100, verbose_name='LD')),
                ('numero_ap', models.CharField(blank=True, default='', help_text='Número da Autorização de Pagamento', max_length=100, verbose_name='AP')),
                ('numero_ap_ex', models.CharField(blank=True, default='', help_text='Número da Autorização de Pagamento Extra Orçamentária', max_length=100, verbose_name='AP EX')),
                ('valor_liquido', models.CharField(blank=True, default='', help_text='Valor Líquido', max_length=100, verbose_name='Valor Líquido')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credor.CredorFornecedor', verbose_name='Credor')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.AddField(
            model_name='consultadepreco',
            name='itens',
            field=models.ManyToManyField(to='processo_pagamento.ItemMaterialDeConsumo'),
        ),
    ]
