# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processopagamento',
            name='natureza_despesa',
            field=models.CharField(choices=[('Diárias [33.90.14.00', 'Diárias [33.90.14.00]'), ('Materia de Consumo [33.90.30.00]', 'Materia de Consumo [33.90.30.00]'), ('Serviços de Pessoa Física [33.90.36.00]', 'Serviços de Pessoa Física [33.90.36.00]'), ('Serviços de Pessoa Jurídica [33.90.39.00]', 'Serviços de Pessoa Jurídica [33.90.39.00]')], max_length=100, verbose_name='Natureza da Despesa'),
        ),
    ]
