# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processodediaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='credorservidor',
            name='codigo_credor',
            field=models.CharField(default='None', help_text='Código do Credor do SIAF', max_length=100, verbose_name='Código do Credor'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='cpf',
            field=models.CharField(default='None', help_text='CPF', max_length=100, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='email',
            field=models.EmailField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='endereco',
            field=models.CharField(default='None', help_text='Endereço do Credor', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='funcacao',
            field=models.CharField(default='None', help_text='Função', max_length=100, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='matricula',
            field=models.CharField(default='None', help_text='Matrícula', max_length=10, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='nome',
            field=models.CharField(default='None', help_text='Nome do Credor', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='credorservidor',
            name='telefone',
            field=models.CharField(default='None', help_text='Telefone do Credor', max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='processodediaria',
            name='destino',
            field=models.CharField(choices=[('Santa Teresinha', 'Santa Teresinha'), ('Congo', 'Congo'), ('Bayeux', 'Bayeux'), ('Aroeiras', 'Aroeiras'), ('Piancó', 'Piancó'), ('Aparecida', 'Aparecida'), ('Areial', 'Areial'), ('Princesa Isabel', 'Princesa Isabel'), ('João Pessoa', 'João Pessoa'), ('Boa Vista', 'Boa Vista'), ('Mae dAgua', 'Mae dAgua'), ('Santa Cecilia', 'Santa Cecilia'), ('Mari', 'Mari'), ('Manaira', 'Manaira'), ('Areia', 'Areia'), ('Guarabira', 'Guarabira'), ('Pedro Regio', 'Pedro Regio'), ('Cajazeiras', 'Cajazeiras'), ('Agua_Branca', 'Agua_Branca'), ('Alagoa Grande', 'Alagoa Grande'), ('Barra de São Miguel', 'Barra de São Miguel'), ('Solanea', 'Solanea'), ('Esperança', 'Esperança'), ('Mataraca', 'Mataraca'), ('Remigio', 'Remigio'), ('Lucena', 'Lucena'), ('Pirpirituba', 'Pirpirituba'), ('Aguiar', 'Aguiar'), ('Jacarau', 'Jacarau'), ('Catingueira', 'Catingueira'), ('Cajazeirinhas', 'Cajazeirinhas'), ('São José de Princesa', 'São José de Princesa'), ('Areia de Baraunas', 'Areia de Baraunas'), ('SÃO José do Sabugi', 'SÃO José do Sabugi'), ('Baia da Traicao', 'Baia da Traicao'), ('Alagoa Nova', 'Alagoa Nova'), ('Caiçara', 'Caiçara'), ('São Domingos do Cariri', 'São Domingos do Cariri'), ('Serra Branca', 'Serra Branca'), ('Sapé', 'Sapé'), ('Bom Jesus', 'Bom Jesus'), ('São José do Brejo do Cruz', 'São José do Brejo do Cruz'), ('Cabaceiras', 'Cabaceiras'), ('Riachao do Poço', 'Riachao do Poço'), ('Juru', 'Juru'), ('Umbuzeiro', 'Umbuzeiro'), ('Gurjão', 'Gurjão'), ('Tacima', 'Tacima'), ('Borborema', 'Borborema'), ('Monteiro', 'Monteiro'), ('Catole do Rocha', 'Catole do Rocha'), ('São Mamede', 'São Mamede'), ('Matureia', 'Matureia'), ('Juazeirinho', 'Juazeirinho'), ('Olivedos', 'Olivedos'), ('Puxinanã', 'Puxinanã'), ('Santo Andre', 'Santo Andre'), ('São Bento', 'São Bento'), ('Desterro', 'Desterro'), ('Nazarezinho', 'Nazarezinho'), ('Santa Luzia', 'Santa Luzia'), ('Sobrado', 'Sobrado'), ('Lagoa Seca', 'Lagoa Seca'), ('Juarez Tavora', 'Juarez Tavora'), ('Mulungu', 'Mulungu'), ('Sousa', 'Sousa'), ('Vista Serrana', 'Vista Serrana'), ('Alhandra', 'Alhandra'), ('Cacimba de Dentro', 'Cacimba de Dentro'), ('Curral Velho', 'Curral Velho'), ('Pocinhos', 'Pocinhos'), ('Bananeiras', 'Bananeiras'), ('Montadas', 'Montadas'), ('Barauna', 'Barauna'), ('Serra Redonda', 'Serra Redonda'), ('Coremas', 'Coremas'), ('Queimadas', 'Queimadas'), ('São José dos Cordeiros', 'São José dos Cordeiros'), ('Serido', 'Serido'), ('Pedras de Fogo', 'Pedras de Fogo'), ('Cachoeira dos Índios', 'Cachoeira dos Índios'), ('Jericó', 'Jericó'), ('Massaranduba', 'Massaranduba'), ('São João do Tigre', 'São João do Tigre'), ('Lagoa de Dentro', 'Lagoa de Dentro'), ('Pitimbu', 'Pitimbu'), ('Riacho de Santo Antonio', 'Riacho de Santo Antonio'), ('Quixaba', 'Quixaba'), ('Patos', 'Patos'), ('Cuitegi', 'Cuitegi'), ('Santa Cruz', 'Santa Cruz'), ('Caraubas', 'Caraubas'), ('Bonito de Santa Fé', 'Bonito de Santa Fé'), ('Itabaiana', 'Itabaiana'), ('Serra da Raiz', 'Serra da Raiz'), ('Cacimba de Areia', 'Cacimba de Areia'), ('Frei Martinho', 'Frei Martinho'), ('Paulista', 'Paulista'), ('Nova Olinda', 'Nova Olinda'), ('Nova Palmeira', 'Nova Palmeira'), ('Vieiropolis', 'Vieiropolis'), ('Matinhas', 'Matinhas'), ('Emas', 'Emas'), ('Sertãozinho', 'Sertãozinho'), ('Sumé', 'Sumé'), ('Alagoinha', 'Alagoinha'), ('Santa Inês', 'Santa Inês'), ('São José dos Ramos', 'São José dos Ramos'), ('Livramento', 'Livramento'), ('Pedra Lavrada', 'Pedra Lavrada'), ('Conceição', 'Conceição'), ('Lagoa Lastro', 'Lagoa Lastro'), ('Barra de Santa Rosa', 'Barra de Santa Rosa'), ('Pedra Branca', 'Pedra Branca'), ('Algodão de Jandaira', 'Algodão de Jandaira'), ('Natuba', 'Natuba'), ('Amparo', 'Amparo'), ('São José de Espinharas', 'São José de Espinharas'), ('Caaporã', 'Caaporã'), ('Taperoá', 'Taperoá'), ('Igaracy', 'Igaracy'), ('Araruna', 'Araruna'), ('Tavares', 'Tavares'), ('Cabedelo', 'Cabedelo'), ('Belem', 'Belem'), ('São Francisco', 'São Francisco'), ('Picuí', 'Picuí'), ('Cacimbas', 'Cacimbas'), ('Sossego', 'Sossego'), ('Belem do Brejo do Cruz', 'Belem do Brejo do Cruz'), ('Aracagi', 'Aracagi'), ('Capim', 'Capim'), ('Zabelê', 'Zabelê'), ('Brejo do Cruz', 'Brejo do Cruz'), ('Barra de Santana', 'Barra de Santana'), ('Salgado de São Felix', 'Salgado de São Felix'), ('Brejo dos Santos', 'Brejo dos Santos'), ('Riachão', 'Riachão'), ('Fagundes', 'Fagundes'), ('Dona Inês', 'Dona Inês'), ('Cubati', 'Cubati'), ('Mato Grosso', 'Mato Grosso'), ('Santa Rita', 'Santa Rita'), ('Campina Grande', 'Campina Grande'), ('Condado', 'Condado'), ('São João do Cariri', 'São João do Cariri'), ('São José de Piranhas', 'São José de Piranhas'), ('Juripiranga', 'Juripiranga'), ('São João do Rio do Peixe', 'São João do Rio do Peixe'), ('Itapororoca', 'Itapororoca'), ('Marcação', 'Marcação'), ('Santa Helena', 'Santa Helena'), ('Camalaú', 'Camalaú'), ('Imaculada', 'Imaculada'), ('Triunfo', 'Triunfo'), ('Boqueirão', 'Boqueirão'), ('Santarem', 'Santarem'), ('Alcantil', 'Alcantil'), ('Itaporanga', 'Itaporanga'), ('Passagem', 'Passagem'), ('Caturite', 'Caturite'), ('Riacho dos Cavalos', 'Riacho dos Cavalos'), ('Soledade', 'Soledade'), ('Damião', 'Damião'), ('Tenorio', 'Tenorio'), ('Teixeira', 'Teixeira'), ('Salgadinho', 'Salgadinho'), ('Itatuba', 'Itatuba'), ('São José de Caiana', 'São José de Caiana'), ('Serraria', 'Serraria'), ('Bernardino Batista', 'Bernardino Batista'), ('Ouro Velho', 'Ouro Velho'), ('Olho dAgua', 'Olho dAgua'), ('Bom Sucesso', 'Bom Sucesso'), ('Pilões', 'Pilões'), ('Monte Horebe', 'Monte Horebe'), ('Caldas Brandão', 'Caldas Brandão'), ('Ibiara', 'Ibiara'), ('Mamanguape', 'Mamanguape'), ('São Sebastiao de Lagoa de Roça', 'São Sebastiao de Lagoa de Roça'), ('São Miguel de Taipu', 'São Miguel de Taipu'), ('Conde', 'Conde'), ('Casserengue', 'Casserengue'), ('Carrapateira', 'Carrapateira'), ('Cuité', 'Cuité'), ('Gurinhem', 'Gurinhem'), ('Malta', 'Malta'), ('Duas Estradas', 'Duas Estradas'), ('Junco do Serido', 'Junco do Serido'), ('Diamante', 'Diamante'), ('Cuité de Mamanguape', 'Cuité de Mamanguape'), ('Boa Ventura', 'Boa Ventura'), ('Curral de Cima', 'Curral de Cima'), ('Santana de Mangueira', 'Santana de Mangueira'), ('Pombal', 'Pombal'), ('Parari', 'Parari'), ('Inga', 'Inga'), ('Riachão do Bacamarte', 'Riachão do Bacamarte'), ('São Domingos de Pombal', 'São Domingos de Pombal'), ('Serra Grande', 'Serra Grande'), ('São José do Bonfim', 'São José do Bonfim'), ('Pilõezinhos', 'Pilõezinhos'), ('Santana dos Garrotes', 'Santana dos Garrotes'), ('Varzea', 'Varzea'), ('São Sebastiao do Umbuzeiro', 'São Sebastiao do Umbuzeiro'), ('Coxixola', 'Coxixola'), ('Poço de José de Moura', 'Poço de José de Moura'), ('Gado Bravo', 'Gado Bravo'), ('Uirauna', 'Uirauna'), ('Arara', 'Arara'), ('São José da Lagoa Tapada', 'São José da Lagoa Tapada'), ('Marizopolis', 'Marizopolis'), ('Cruz do Espirito Santo', 'Cruz do Espirito Santo'), ('Nova Floresta', 'Nova Floresta'), ('Logradouro', 'Logradouro'), ('Poco Dantas', 'Poco Dantas'), ('Prata', 'Prata'), ('Assuncao', 'Assuncao'), ('Pilar', 'Pilar'), ('Rio Tinto', 'Rio Tinto'), ('Mogeiro', 'Mogeiro')], max_length=100, verbose_name='Destino'),
        ),
    ]
