# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170928_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credorfornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='credorservidor',
            options={'verbose_name': 'Credor', 'verbose_name_plural': 'Credores'},
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='cnpj',
            field=models.CharField(default='None', help_text='CNPJ', max_length=100, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='codigo_credor',
            field=models.CharField(default='None', help_text='Código do Credor do SIAF', max_length=100, verbose_name='Código do Credor'),
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='email',
            field=models.EmailField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='endereco',
            field=models.CharField(default='None', help_text='Endereço do Credor', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='nome',
            field=models.CharField(default='None', help_text='Nome do Credor', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='credorfornecedor',
            name='telefone',
            field=models.CharField(default='None', help_text='Telefone do Credor', max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='processodediaria',
            name='destino',
            field=models.CharField(choices=[('Cabaceiras', 'Cabaceiras'), ('Barra de São Miguel', 'Barra de São Miguel'), ('Alcantil', 'Alcantil'), ('Serraria', 'Serraria'), ('Inga', 'Inga'), ('Cuité', 'Cuité'), ('Serra Grande', 'Serra Grande'), ('Bernardino Batista', 'Bernardino Batista'), ('Piancó', 'Piancó'), ('Damião', 'Damião'), ('Livramento', 'Livramento'), ('Riacho dos Cavalos', 'Riacho dos Cavalos'), ('Igaracy', 'Igaracy'), ('Sumé', 'Sumé'), ('Caiçara', 'Caiçara'), ('SÃO José do Sabugi', 'SÃO José do Sabugi'), ('Fagundes', 'Fagundes'), ('Camalaú', 'Camalaú'), ('Taperoá', 'Taperoá'), ('Soledade', 'Soledade'), ('Teixeira', 'Teixeira'), ('São Miguel de Taipu', 'São Miguel de Taipu'), ('Brejo do Cruz', 'Brejo do Cruz'), ('Gurinhem', 'Gurinhem'), ('Ibiara', 'Ibiara'), ('Barra de Santa Rosa', 'Barra de Santa Rosa'), ('Baia da Traicao', 'Baia da Traicao'), ('Alagoa Grande', 'Alagoa Grande'), ('Diamante', 'Diamante'), ('Imaculada', 'Imaculada'), ('Aguiar', 'Aguiar'), ('Cacimba de Dentro', 'Cacimba de Dentro'), ('Pilõezinhos', 'Pilõezinhos'), ('Santa Rita', 'Santa Rita'), ('São João do Cariri', 'São João do Cariri'), ('Juarez Tavora', 'Juarez Tavora'), ('Boa Vista', 'Boa Vista'), ('Aracagi', 'Aracagi'), ('São José de Piranhas', 'São José de Piranhas'), ('Poco Dantas', 'Poco Dantas'), ('Belem do Brejo do Cruz', 'Belem do Brejo do Cruz'), ('São José do Bonfim', 'São José do Bonfim'), ('Esperança', 'Esperança'), ('Serra Redonda', 'Serra Redonda'), ('Serra da Raiz', 'Serra da Raiz'), ('Santarem', 'Santarem'), ('Itapororoca', 'Itapororoca'), ('Riachao do Poço', 'Riachao do Poço'), ('Parari', 'Parari'), ('Quixaba', 'Quixaba'), ('Areia', 'Areia'), ('Carrapateira', 'Carrapateira'), ('Manaira', 'Manaira'), ('Triunfo', 'Triunfo'), ('Santa Teresinha', 'Santa Teresinha'), ('Lagoa de Dentro', 'Lagoa de Dentro'), ('Serido', 'Serido'), ('São José dos Ramos', 'São José dos Ramos'), ('Prata', 'Prata'), ('Lagoa Lastro', 'Lagoa Lastro'), ('Cabedelo', 'Cabedelo'), ('Cajazeirinhas', 'Cajazeirinhas'), ('Santa Cecilia', 'Santa Cecilia'), ('Bom Jesus', 'Bom Jesus'), ('Itatuba', 'Itatuba'), ('Brejo dos Santos', 'Brejo dos Santos'), ('Olho dAgua', 'Olho dAgua'), ('Tacima', 'Tacima'), ('Tavares', 'Tavares'), ('Nova Olinda', 'Nova Olinda'), ('Jacarau', 'Jacarau'), ('Casserengue', 'Casserengue'), ('São Sebastiao de Lagoa de Roça', 'São Sebastiao de Lagoa de Roça'), ('Passagem', 'Passagem'), ('Santa Cruz', 'Santa Cruz'), ('Solanea', 'Solanea'), ('Juru', 'Juru'), ('Sobrado', 'Sobrado'), ('Puxinanã', 'Puxinanã'), ('Dona Inês', 'Dona Inês'), ('Juripiranga', 'Juripiranga'), ('Duas Estradas', 'Duas Estradas'), ('Santa Helena', 'Santa Helena'), ('Pirpirituba', 'Pirpirituba'), ('Gurjão', 'Gurjão'), ('Santana dos Garrotes', 'Santana dos Garrotes'), ('Sapé', 'Sapé'), ('Varzea', 'Varzea'), ('Caldas Brandão', 'Caldas Brandão'), ('Pombal', 'Pombal'), ('Matinhas', 'Matinhas'), ('Desterro', 'Desterro'), ('Coremas', 'Coremas'), ('Zabelê', 'Zabelê'), ('Monte Horebe', 'Monte Horebe'), ('Picuí', 'Picuí'), ('São Domingos de Pombal', 'São Domingos de Pombal'), ('Umbuzeiro', 'Umbuzeiro'), ('Mataraca', 'Mataraca'), ('Vista Serrana', 'Vista Serrana'), ('Mamanguape', 'Mamanguape'), ('Borborema', 'Borborema'), ('Pilar', 'Pilar'), ('Boa Ventura', 'Boa Ventura'), ('Congo', 'Congo'), ('Areial', 'Areial'), ('Marizopolis', 'Marizopolis'), ('São Bento', 'São Bento'), ('Nazarezinho', 'Nazarezinho'), ('Malta', 'Malta'), ('Mari', 'Mari'), ('Riachão do Bacamarte', 'Riachão do Bacamarte'), ('Mogeiro', 'Mogeiro'), ('São José da Lagoa Tapada', 'São José da Lagoa Tapada'), ('São Domingos do Cariri', 'São Domingos do Cariri'), ('Santa Inês', 'Santa Inês'), ('Salgadinho', 'Salgadinho'), ('São João do Rio do Peixe', 'São João do Rio do Peixe'), ('Aparecida', 'Aparecida'), ('Vieiropolis', 'Vieiropolis'), ('Aroeiras', 'Aroeiras'), ('Caraubas', 'Caraubas'), ('Bonito de Santa Fé', 'Bonito de Santa Fé'), ('Algodão de Jandaira', 'Algodão de Jandaira'), ('Lagoa Seca', 'Lagoa Seca'), ('Natuba', 'Natuba'), ('Pocinhos', 'Pocinhos'), ('Cachoeira dos Índios', 'Cachoeira dos Índios'), ('Conde', 'Conde'), ('Mulungu', 'Mulungu'), ('João Pessoa', 'João Pessoa'), ('Pitimbu', 'Pitimbu'), ('Catole do Rocha', 'Catole do Rocha'), ('Pilões', 'Pilões'), ('São Sebastiao do Umbuzeiro', 'São Sebastiao do Umbuzeiro'), ('Amparo', 'Amparo'), ('Alagoa Nova', 'Alagoa Nova'), ('Barra de Santana', 'Barra de Santana'), ('Pedra Branca', 'Pedra Branca'), ('Caturite', 'Caturite'), ('Jericó', 'Jericó'), ('Condado', 'Condado'), ('Olivedos', 'Olivedos'), ('Areia de Baraunas', 'Areia de Baraunas'), ('São Francisco', 'São Francisco'), ('Guarabira', 'Guarabira'), ('Paulista', 'Paulista'), ('São Mamede', 'São Mamede'), ('Pedra Lavrada', 'Pedra Lavrada'), ('Logradouro', 'Logradouro'), ('São José de Caiana', 'São José de Caiana'), ('São João do Tigre', 'São João do Tigre'), ('Bananeiras', 'Bananeiras'), ('Gado Bravo', 'Gado Bravo'), ('Catingueira', 'Catingueira'), ('Remigio', 'Remigio'), ('Cacimbas', 'Cacimbas'), ('São José do Brejo do Cruz', 'São José do Brejo do Cruz'), ('Belem', 'Belem'), ('Pedro Regio', 'Pedro Regio'), ('Curral de Cima', 'Curral de Cima'), ('Campina Grande', 'Campina Grande'), ('Arara', 'Arara'), ('Boqueirão', 'Boqueirão'), ('Queimadas', 'Queimadas'), ('Monteiro', 'Monteiro'), ('Sousa', 'Sousa'), ('São José de Princesa', 'São José de Princesa'), ('Serra Branca', 'Serra Branca'), ('Alhandra', 'Alhandra'), ('Cuité de Mamanguape', 'Cuité de Mamanguape'), ('Mato Grosso', 'Mato Grosso'), ('Barauna', 'Barauna'), ('Sertãozinho', 'Sertãozinho'), ('Bom Sucesso', 'Bom Sucesso'), ('Cubati', 'Cubati'), ('Riachão', 'Riachão'), ('Santo Andre', 'Santo Andre'), ('Agua_Branca', 'Agua_Branca'), ('Princesa Isabel', 'Princesa Isabel'), ('Assuncao', 'Assuncao'), ('São José dos Cordeiros', 'São José dos Cordeiros'), ('Ouro Velho', 'Ouro Velho'), ('Pedras de Fogo', 'Pedras de Fogo'), ('Araruna', 'Araruna'), ('Nova Palmeira', 'Nova Palmeira'), ('Matureia', 'Matureia'), ('Massaranduba', 'Massaranduba'), ('Riacho de Santo Antonio', 'Riacho de Santo Antonio'), ('Rio Tinto', 'Rio Tinto'), ('Emas', 'Emas'), ('Itaporanga', 'Itaporanga'), ('Capim', 'Capim'), ('Mae dAgua', 'Mae dAgua'), ('Marcação', 'Marcação'), ('Curral Velho', 'Curral Velho'), ('Montadas', 'Montadas'), ('Itabaiana', 'Itabaiana'), ('Salgado de São Felix', 'Salgado de São Felix'), ('Frei Martinho', 'Frei Martinho'), ('Patos', 'Patos'), ('Cruz do Espirito Santo', 'Cruz do Espirito Santo'), ('Poço de José de Moura', 'Poço de José de Moura'), ('Nova Floresta', 'Nova Floresta'), ('Uirauna', 'Uirauna'), ('Coxixola', 'Coxixola'), ('São José de Espinharas', 'São José de Espinharas'), ('Cajazeiras', 'Cajazeiras'), ('Cacimba de Areia', 'Cacimba de Areia'), ('Sossego', 'Sossego'), ('Lucena', 'Lucena'), ('Bayeux', 'Bayeux'), ('Tenorio', 'Tenorio'), ('Caaporã', 'Caaporã'), ('Santana de Mangueira', 'Santana de Mangueira'), ('Juazeirinho', 'Juazeirinho'), ('Santa Luzia', 'Santa Luzia'), ('Conceição', 'Conceição'), ('Cuitegi', 'Cuitegi'), ('Junco do Serido', 'Junco do Serido'), ('Alagoinha', 'Alagoinha')], max_length=100, verbose_name='Destino'),
        ),
    ]
