# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredorFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='None', help_text='Nome do Credor', max_length=100, verbose_name='Nome')),
                ('codigo_credor', models.CharField(default='None', help_text='Código do Credor do SIAF', max_length=100, verbose_name='Código do Credor')),
                ('telefone', models.CharField(default='None', help_text='Telefone do Credor', max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(default='None', max_length=100)),
                ('endereco', models.CharField(default='None', help_text='Endereço do Credor', max_length=100, verbose_name='Endereço')),
                ('cnpj', models.CharField(default='None', help_text='CNPJ', max_length=100, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='CredorServidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='None', help_text='Nome do Credor', max_length=100, verbose_name='Nome')),
                ('codigo_credor', models.CharField(default='None', help_text='Código do Credor do SIAF', max_length=100, verbose_name='Código do Credor')),
                ('telefone', models.CharField(default='None', help_text='Telefone do Credor', max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(default='None', max_length=100)),
                ('endereco', models.CharField(default='None', help_text='Endereço do Credor', max_length=100, verbose_name='Endereço')),
                ('matricula', models.CharField(default='None', help_text='Matrícula', max_length=10, verbose_name='Matrícula')),
                ('funcacao', models.CharField(default='None', help_text='Função', max_length=100, verbose_name='Função')),
                ('cpf', models.CharField(default='None', help_text='CPF', max_length=100, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Credor',
                'verbose_name_plural': 'Credores',
            },
        ),
    ]
