# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processodediaria',
            name='valor',
            field=models.CharField(blank=True, default='', help_text='Valor da Diária', max_length=100, verbose_name='Valor'),
        ),
    ]
